---
satellite_package: satellite
satellite_installer_cmd: satellite-installer
satellite_scenario: satellite
capsule_puppet_module: foreman-proxy
satellite_installer_options: "--foreman-ipa-authentication false --reset-puppet-server-ssl-chain-filepath --disable-system-checks"
satellite_upgrade_options: "--disable-system-checks"
verify_rake_task: reimport