---
satellite_package: satellite
satellite_installer_cmd: satellite-installer
satellite_scenario: satellite
capsule_puppet_module: foreman-proxy
satellite_installer_options: "--foreman-ipa-authentication false"
verify_rake_task: reimport
sp_features_table_name: features_smart_proxies
