- name: Stop katello services
  command: katello-service stop

- name: Stop postgresql
  service: name=postgresql state=stopped

- name: Restore postgresql data
  command: tar --selinux --overwrite -xvf {{ backup_dir }}/pgsql_data.tar.gz -C /

- name: Start postgresql
  service: name=postgresql state=started

- name: Restore mongo data
  command: tar --selinux --overwrite -xvf {{ backup_dir }}/mongo_data.tar.gz -C /

- unarchive:
    src: {{ backup_dir }}/pulp_data.tar
    dest: /

- name: Start mongod
  service: name=mongod state=started

- name: migrate pulp db
  command: sudo -u apache pulp-manage-db
