---
- name: "check that variables are updated"
  fail: msg="Please update the variables in roles/satellite-hostname/vars/main.yml"
  when:
    - new_hostname == "changeme"
    - admin_username == "changeme"
    - admin_password == "changeme"

# need to change from my fork when https://github.com/Katello/katello-packaging/pull/323/files is merged
- name: download katello-change-hostname script
  get_url:
    url: https://raw.githubusercontent.com/Katello/katello-packaging/master/katello/katello-change-hostname
    dest: /tmp/katello-change-hostname
    mode: 0755

- name: run hostname change script
  shell: yes | /tmp/katello-change-hostname {{ new_hostname }} --username {{ admin_username }} --password {{ admin_password }}
  register: run_hostname_change

- name: copy logs
  local_action: copy content={{ run_hostname_change.stdout }} dest=./logs/satellite-hostname.log

- debug: msg="Hostname change completed successfully. Look at logs/change-hostname.log (in satellite-clone root directory) for further post-script instructions"
  when: run_hostname_change | success

- debug: msg="Hostname change failed. Check logs/change-hostname.log (in satellite-clone root directory) for details"
  when: run_hostname_change | failed
